version: '3.3'
services:
    couchbase:
        image: couchbase/server:6.6.5
        deploy:
            replicas: 1
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 8094:8094
            - 11210:11210
        volumes:
            - "./setup-couchbase.sh:/opt/couchbase/setup-couchbase.sh"
            - "./lytx_registration_sample_data.json:/opt/couchbase/lytx_registration_sample_data.json"
        command: 
            - /opt/couchbase/setup-couchbase.sh
