version: '3.3'
services:
    couchbase:
        tty: true
        image: couchbase/server
        deploy:
            replicas: 1
        restart: always
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 8094:8094
            - 11210:11210
        volumes:
            - "./setup-couchbase.sh:/opt/couchbase/setup-couchbase.sh"
            - "./mapTestData.json:/opt/couchbase/mapTestData.json"
        command: 
            - /opt/couchbase/setup-couchbase.sh
