# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/player.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/player.proto\x12\x05\x63\x61\x63he\"\x17\n\tPlayer_id\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x0bPlayerModel\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1f\n\rCacheResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2}\n\x06Player\x12\x39\n\x0b\x43\x61\x63hePlayer\x12\x12.cache.PlayerModel\x1a\x14.cache.CacheResponse\"\x00\x12\x38\n\x0eGetCachePlayer\x12\x10.cache.Player_id\x1a\x12.cache.PlayerModel\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.player_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYER_ID._serialized_start=30
  _PLAYER_ID._serialized_end=53
  _PLAYERMODEL._serialized_start=55
  _PLAYERMODEL._serialized_end=101
  _CACHERESPONSE._serialized_start=103
  _CACHERESPONSE._serialized_end=134
  _PLAYER._serialized_start=136
  _PLAYER._serialized_end=261
# @@protoc_insertion_point(module_scope)
