# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from .player_pb2 import *


class PlayerCacheGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CachePlayer = channel.unary_unary(
                '/cache.PlayerCacheGRPC/CachePlayer',
                request_serializer=PlayerToCache.SerializeToString,
                response_deserializer=CacheResponse.FromString,
                )
        self.GetCachePlayer = channel.unary_unary(
                '/cache.PlayerCacheGRPC/GetCachePlayer',
                request_serializer=Player_id.SerializeToString,
                response_deserializer=PlayerToCache.FromString,
                )


class PlayerCacheGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CachePlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCachePlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerCacheGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CachePlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.CachePlayer,
                    request_deserializer=PlayerToCache.FromString,
                    response_serializer=CacheResponse.SerializeToString,
            ),
            'GetCachePlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCachePlayer,
                    request_deserializer=Player_id.FromString,
                    response_serializer=PlayerToCache.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache.PlayerCacheGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerCacheGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CachePlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.PlayerCacheGRPC/CachePlayer',
            PlayerToCache.SerializeToString,
            CacheResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCachePlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.PlayerCacheGRPC/GetCachePlayer',
            Player_id.SerializeToString,
            PlayerToCache.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
